image: archlinux
packages:
  - go
sources:
  - https://github.com/go-ap/errors
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd errors && go mod download
  - tests: |
      cd errors
      go test -v ./...
